nomes = ["Pedro", "José", "Paulo"]
print(nomes[1])
print(nomes[0])
nomes.append("Juliana")
print(nomes)
nomes.insert(0, "Jonas")
print(nomes)
nomes.append("Cremilda")
print(nomes)
nomes.remove("José")
print(nomes)
nomes.insert(2, "Huguinho")
print(nomes)
nomes.clear()
